In [1]:
import numpy as np

In [30]:
seq1='HHFGTYH'
seq2='HFGGGH'

In [31]:
m_seq1=len(seq1)+1
m_seq2=len(seq2)+1

In [32]:
matrix=np.zeros((m_seq1,m_seq2))
matrix

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [33]:
sim_matrix=np.zeros((m_seq1-1,m_seq2-1))
for i in range(len(seq1)):
  for j in range(len(seq2)):
    if seq1[i]==seq2[j]:
      sim_matrix[i][j]=1
    else:
      sim_matrix[i][j]=0

In [34]:
sim_matrix

array([[1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 1.]])

In [35]:
g_penalty=-1

In [36]:
def nw_algorithm(matrix):
  for i in range(m_seq1):
    matrix[i][0]=i*g_penalty
  for j in range(m_seq2):
    matrix[0][j]=j*g_penalty
  for i in range(1,m_seq1):
    for j in range(1,m_seq2):
      matrix[i][j]=max(matrix[i-1][j-1]+sim_matrix[i-1][j-1],matrix[i-1][j]+g_penalty,matrix[i][j-1]+g_penalty)
  return(matrix)

In [37]:
nw_algorithm(matrix)

array([[ 0., -1., -2., -3., -4., -5., -6.],
       [-1.,  1.,  0., -1., -2., -3., -4.],
       [-2.,  0.,  1.,  0., -1., -2., -2.],
       [-3., -1.,  1.,  1.,  0., -1., -2.],
       [-4., -2.,  0.,  2.,  2.,  1.,  0.],
       [-5., -3., -1.,  1.,  2.,  2.,  1.],
       [-6., -4., -2.,  0.,  1.,  2.,  2.],
       [-7., -5., -3., -1.,  0.,  1.,  3.]])

In [38]:
AlignmentA=''
AlignmentB=''

i = len(seq1)
j = len(seq2)

while (i >0 or j >0):

  if (i > 0 and j > 0 and matrix[i][j] == matrix[i-1][j-1] + sim_matrix[i-1][j-1]):
  
    AlignmentA=seq1[i-1] + AlignmentA
    AlignmentB=seq2[j-1] + AlignmentB
    i=i - 1
    j=j - 1

  elif (i > 0 and matrix[i][j] == matrix[i-1][j] + g_penalty):
  
    AlignmentA=seq1[i-1] + AlignmentA
    AlignmentB="-" + AlignmentB
    i=i - 1
  
  else:
  
    AlignmentA="-" + AlignmentA
    AlignmentB=seq2[j-1] + AlignmentB
    j=j - 1

In [39]:
AlignmentA

'HHFGTYH'

In [40]:
AlignmentB

'-HFGGGH'